Algoritmo "semnome"

Var
n1,n2,soma, dife, prod, med:real
Inicio
Escreval("Entre com um numero")
Leia(n1)
Escreval("Entre com outro numero")
Leia (n2)

soma<- n1+n2
dife<- n1-n2
prod<- n1*n2
med<- (n1+n2)/2

escreval ("resultado da soma ", soma)
escreval ("resultado da diferenteça ", dife)
escreval ("resultado do produto ", prod)
escreval ("resultado da media ", med)

Fimalgoritmo